sudo: false
language: ruby
rvm:
  - 2.3.0
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - gem install bundler -v 1.12.5
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec thermite:build
