[package]

name = "rust_watcher"
version = "0.1.0"
authors = ["Dave Allie"]
repository = "https://github.com/daveallie/rust_watcher"
publish = false

[package.metadata.thermite]

github_releases = true

[lib]

crate-type = ["dylib"]

[dependencies]

ruru = "0.8"
notify = "2.6.3"
